### ISSUE TITLE
Package broken due to wrong brotli dependency

### ISSUE THREAD

**Issue by xhochy** [AnacondaRecipes/urllib3-feedstock#2]
Since the last build this package depends on the C package `brotli` instead of the Python package `brotlipy`. 

The respective change is https://github.com/AnacondaRecipes/urllib3-feedstock/commit/4549012f422f2301c8bb676a3df0eec5b633a4e6

This leads to `conda` errors on Windows as e.g.:

```
2021-06-30T18:27:07.0760749Z Traceback (most recent call last):
2021-06-30T18:27:07.0761405Z   File "C:\Miniconda\Scripts\conda-script.py", line 12, in <module>
2021-06-30T18:27:07.0762040Z     sys.exit(main())
2021-06-30T18:27:07.0762678Z   File "C:\Miniconda\lib\site-packages\conda\cli\main.py", line 152, in main
2021-06-30T18:27:07.0763386Z     return conda_exception_handler(_main, *args, **kwargs)
2021-06-30T18:27:07.0764129Z   File "C:\Miniconda\lib\site-packages\conda\exceptions.py", line 1371, in conda_exception_handler
2021-06-30T18:27:07.0764848Z     return_value = exception_handler(func, *args, **kwargs)
2021-06-30T18:27:07.0765564Z   File "C:\Miniconda\lib\site-packages\conda\exceptions.py", line 1082, in __call__
2021-06-30T18:27:07.0766272Z     return self.handle_exception(exc_val, exc_tb)
2021-06-30T18:27:07.0767163Z   File "C:\Miniconda\lib\site-packages\conda\exceptions.py", line 1126, in handle_exception
2021-06-30T18:27:07.0768161Z     return self.handle_unexpected_exception(exc_val, exc_tb)
2021-06-30T18:27:07.0768985Z   File "C:\Miniconda\lib\site-packages\conda\exceptions.py", line 1137, in handle_unexpected_exception
2021-06-30T18:27:07.0771469Z     self.print_unexpected_error_report(error_report)
2021-06-30T18:27:07.0772341Z   File "C:\Miniconda\lib\site-packages\conda\exceptions.py", line 1207, in print_unexpected_error_report
2021-06-30T18:27:07.0773171Z     from .cli.main_info import get_env_vars_str, get_main_info_str
2021-06-30T18:27:07.0774112Z   File "C:\Miniconda\lib\site-packages\conda\cli\main_info.py", line 19, in <module>
2021-06-30T18:27:07.0774841Z     from ..core.index import _supplement_index_with_system
2021-06-30T18:27:07.0775600Z   File "C:\Miniconda\lib\site-packages\conda\core\index.py", line 13, in <module>
2021-06-30T18:27:07.0776289Z     from .package_cache_data import PackageCacheData
2021-06-30T18:27:07.0777112Z   File "C:\Miniconda\lib\site-packages\conda\core\package_cache_data.py", line 14, in <module>
2021-06-30T18:27:07.0777855Z     from .path_actions import CacheUrlAction, ExtractPackageAction
2021-06-30T18:27:07.0778600Z   File "C:\Miniconda\lib\site-packages\conda\core\path_actions.py", line 30, in <module>
2021-06-30T18:27:07.0779428Z     from ..gateways.connection.download import download
2021-06-30T18:27:07.0780188Z   File "C:\Miniconda\lib\site-packages\conda\gateways\connection\__init__.py", line 21, in <module>
2021-06-30T18:27:07.0780938Z     from requests import ConnectionError, HTTPError, Session
2021-06-30T18:27:07.0782478Z   File "C:\Miniconda\lib\site-packages\requests\__init__.py", line 43, in <module>
2021-06-30T18:27:07.0783136Z     import urllib3
2021-06-30T18:27:07.0783809Z   File "C:\Miniconda\lib\site-packages\urllib3\__init__.py", line 13, in <module>
2021-06-30T18:27:07.0784583Z     from .connectionpool import HTTPConnectionPool, HTTPSConnectionPool, connection_from_url
2021-06-30T18:27:07.0785341Z   File "C:\Miniconda\lib\site-packages\urllib3\connectionpool.py", line 40, in <module>
2021-06-30T18:27:07.0786215Z     from .response import HTTPResponse
2021-06-30T18:27:07.0787095Z   File "C:\Miniconda\lib\site-packages\urllib3\response.py", line 157, in <module>
2021-06-30T18:27:07.0787835Z     class HTTPResponse(io.IOBase):
2021-06-30T18:27:07.0788729Z   File "C:\Miniconda\lib\site-packages\urllib3\response.py", line 390, in HTTPResponse
2021-06-30T18:27:07.0790048Z     DECODER_ERROR_CLASSES += (brotli.error,)
2021-06-30T18:27:07.0791121Z AttributeError: module 'brotli' has no attribute 'error'
```

cc @chenglee @skupr-anaconda @anaconda-pkg-build

**Comment by chenghlee** [comment]
The broken urllib3=1.26.6 package has been yanked from defaults. We'll update our recipe and re-release it, but in the meantime, this should at least stop on-going breaks.

**Comment by pseudoyim** [comment]
Built and uploaded: https://repo.anaconda.com/pkgs/main/noarch/urllib3-1.26.6-pyhd3eb1b0_1.tar.bz2

**Comment by isuruf** [comment]
Thanks @xhochy for investigating and @chenghlee and @pseudoyim for the quick fix.
